# Generated by Django 5.1.5 on 2025-01-30 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talent', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='talent',
            name='reference_id',
            field=models.CharField(max_length=256, unique=True),
        ),
    ]
